spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300

#elasticsearch.clustername: elasticsearch
#elasticsearch.host: localhost
#
#elasticsearch.port: 9300