package com.example.base.java.demobasejava.generic_type_erasure;

/**
 * @author benjamin
 * created at 2019/7/9
 */
public class MyNode extends Node<Integer> {
    public MyNode(Integer data) {
        super(data);
    }


    // 桥方法
    public void setData(Integer data) {
        System.out.println("MyNode.setData");
        super.setData(data);
    }
}

/**
 * class MyNode extends Node {
 *
 *     // Bridge method generated by the compiler
 *     // 编译器生成的桥方法
 *
 *     public void setData(Object data) {
 *         setData((Integer) data);
 *     }
 *
 *     public void setData(Integer data) {
 *         System.out.println("MyNode.setData");
 *         super.setData(data);
 *     }
 *
 *     // ...
 * }
 * */